version: "3.7"

services:
  web:
    image: node:14
    environment:
      NODE_ENV: production
      SECRET_KEY: "hardcoded-secret-key" # Hardcoded sensitive data
      DB_PASSWORD: "password123" # Hardcoded sensitive data
    ports:
      - "80:3000" # Exposing HTTP port publicly
    volumes:
      - .:/app
    command: ["node", "server.js"]
    user: root # Running as root (vulnerability)

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword" # Hardcoded sensitive data
      MYSQL_DATABASE: "testdb"
    ports:
      - "3306:3306" # Exposing database port publicly
    volumes:
      - db_data:/var/lib/mysql
    user: root # Running as root (vulnerability)

volumes:
  db_data:
